export enum USER_ACTION_TYPES {
  SET_CURRENT_USER = 'user/SET_CURRENT_USER',
  CHECK_USER_SESSION = 'user/CHECK_USER_SESSION',
  GOOGLE_SIGN_IN = 'user/GOOGLE_SIGN_IN',
  EMAIL_AND_PASSWORD_SIGN_IN = 'user/EMAIL_AND_PASSWORD_SIGN_IN',
  SIGN_IN_SUCCESS = 'user/SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE = 'user/SIGN_IN_FAILURE',
  FETCH_USER = 'user/FETCH_USER',
}
