export enum CART_ACTION_TYPES {
  ADD_TO_CART = "cart/ADD_TO_CART",
  REMOVE_FROM_CART = "cart/REMOVE_FROM_CART",
  SET_DISCOUNT = "cart/SET_DISCOUNT",
  SET_SHIPPING = "cart/SET_SHIPPING",
  INCREASE_PRODUCT_QUANTITY = "cart/INCREASE_PRODUCT_QUANTITY",
  DECREASE_PRODUCT_QUANTITY = "cart/DECREASE_PRODUCT_QUANTITY",
  CLEAR_CART = "cart/CLEAR_CART",
}
